---
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: capstone
    labels:
      app: capstone-mlapp
    namespace: default
  spec:
    replicas: 2
    selector:
      matchLabels:
        app: capstone-mlapp
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        labels:
          app: capstone-mlapp
      spec:
        containers:
        - image: monkbilal/mlapp:latest
          imagePullPolicy: Always
          name: capstone-mlapp
          ports:
          - containerPort: 80
            protocol: TCP
          resources:
            limits:
              cpu: "1"
              memory: 200Mi
            requests:
              cpu: "0.5"
              memory: "150"

---
  apiVersion: v1
  kind: Service
  metadata:
    name: capstone-mlapp-service
  spec:
    selector:
      app: capstone-mlapp
    type: LoadBalancer
    ports:
      -  protocol: TCP
         targetPort: 80
         port: 80

